import Head from 'next/head';
import Hero from '../components/Homepage/Hero';
import Layout from '../components/Layout/Layout';
import WhyYoga from '../components/Homepage/WhyYoga';
import Training from '../components/Homepage/Training';
import Class from '../components/Homepage/Class';
import Team from '../components/Homepage/Team';
import Testimonial from '../components/Homepage/Testimonial';

import { useEffect } from 'react';

export default function Home() {

  return (
    <Layout>
      <Head>
        <title>YogaYatra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <WhyYoga />
      <Training />
      <Class />
      <Team />
      <Testimonial />
    </Layout>
  )
}
